#CI项目
name: HanzWrt-X86

#CI计划
on:
  #自动编译：当Auto-Clean运行完成后
  workflow_run:
    workflows: ["Auto-Clean"]
    types:
      - completed
  #手动编译
  workflow_dispatch:
    inputs:
      TEST:
        description: '仅输出配置文件，不编译固件。'
        default: 'false'
        required: false
        type: boolean

#CI权限
permissions: write-all

#CI任务
jobs:
  config:
    name: ${{matrix.TARGET}}
    strategy:
      fail-fast: false
      #max-parallel: 3
      matrix:
        TARGET: [X86]
        SOURCE: [immortalwrt/immortalwrt]
        BRANCH: [openwrt-24.10]

    #调用公用编译核心WRT-CORE.yml
    uses: ./.github/workflows/HanzWrt-Core.yml
    with:
      #编译平台
      WRT_TARGET: ${{matrix.TARGET}}
      #默认主题
      WRT_THEME: argon
      #默认主机名
      WRT_NAME: HanzWrt
      #默认地址
      WRT_IP: ${{ secrets.PROXY_ADDR }}
      #源码链接
      WRT_REPO: https://github.com/${{matrix.SOURCE}}.git
      #源码分支
      WRT_BRANCH: ${{matrix.BRANCH}}
      #仅输出配置文件
      WRT_TEST: ${{inputs.TEST}}
